# Uncomment the following lines to enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Enable sleep for power saving on the keyboard peripheral
CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable Hybrid Dynamic Role configuration
CONFIG_ZMK_UNIBODY_HYBRID=y

# Configure split peripheral role for DONGLE mode
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
