# Enable RGB underglow control code (so keymap behaviors compile)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Boost Bluetooth transmission power to +8dBm
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable split central role
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Disable hybrid mode on the Dongle
CONFIG_ZMK_UNIBODY_HYBRID=n

# Enable USB logging for debugging
CONFIG_ZMK_USB_LOGGING=y
