# Disable RGB underglow on the dongle (no physical LEDs)
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n

# Disable sleep on the dongle (always powered via USB)
CONFIG_ZMK_SLEEP=n

# Boost Bluetooth transmission power to +8dBm
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
