manifest:
  remotes:
    - name: tienanhnguyen996
      url-base: https://github.com/tienanhnguyen996
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: tienanhnguyen996
      revision: main
      import: app/west.yml
  self:
    path: config
