# Enable split central
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Support 1 peripheral (our split peripheral)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Disable hybrid mode on the Dongle
CONFIG_ZMK_UNIBODY_HYBRID=n
